/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void)
{
    printf("The size of the char data type is: %u\n", sizeof(char)); // size is unsigned
    printf("The size of the short data type is: %u\n", sizeof(short));
    printf("The size of the int data type is: %u\n", sizeof(int));
    printf("The size of the long data type is: %u\n", sizeof(long));
    printf("The size of the long long data type is: %u\n", sizeof(long long));
    printf("The size of the double data type is: %u\n", sizeof(double));

	for(;;);
}
